apiVersion: apps/v1

kind: Deployment  

metadata: 
  name: deploymentexternal-deployment
  labels:
    app: deploymentexternal
    type: frontend

spec:
  template:
    metadata:
      name: deploymentexternal-pod
      labels:
        app: deploymentexternal
        tier: frontend
    spec:
      containers:
      - name: deploymentexternal-container
        image: amrkhan28/ext:1.0
        env: 
          - name: SERVER
            value: "http://devops-internal:8082"
        ports:
          - containerPort: 8080

  replicas: 2

  selector:
    matchLabels:
      app: deploymentexternal
