apiVersion: v1
kind: Service
metadata:
  name: deploymentexternal-loadbalancer
  labels:
    app: deploymentexternal
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: deploymentexternal
    